// <auto-generated />
using DW.Rental.Data.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DW.Rendal.Data.Migrations;

[DbContext(typeof(LocationDbContext))]
[Migration("20240415221940_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("DW.Rendal.Data.Entities.Motorcycle", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Ano")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Modelo")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Placa")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Id")
                    .IsUnique();

                b.HasIndex("Placa")
                    .IsUnique();

                b.ToTable("Motocycle", "dbo");
            });
#pragma warning restore 612, 618
    }
}
